baseURL = 'https://hcy.life/'
languageCode = 'zh-CN'
theme = ["newsroom"]
cleanDestinationDir = true
enableGitInfo = true
hasCJKLanguage = true
defaultContentLanguage = "zh"
canonifyurls = true
paginate = 6
title = "H.C.yan"
author = "HCY"