baseURL = 'https://hcy.life/'
languageCode = 'zh-CN'
theme = ["hello"]
cleanDestinationDir = true
enableGitInfo = true
hasCJKLanguage = true
defaultContentLanguage = "zh"
canonifyurls = true
title = "H.C.yan"
author = "HCY"
uglyURLs = true
[menu]
  [[menu.main]]
    identifier = "archive"
    name = "归档"
    url = "/archives/"
