baseURL = 'https://hcy.life/'
languageCode = 'zh-CN'
theme = ["newsroom"]
author = "hcy"
cleanDestinationDir = true
enableGitInfo = true
hasCJKLanguage = true
defaultContentLanguage = "zh"
canonifyurls = true
paginate = 6
title = "HCY"
subtitle = "hcy.life"